[project]
name = "betterbranch"
description = "BetterBranch is a tiny command-line tool that reports the ahead/behind status of all local Git branches relative to the current branch."
longDescription = "BetterBranch is a tiny command-line tool that reports the ahead/behind status of all local Git branches relative to the current branch."
authors = [ "Benjamin Marwell" ]
license = "EUPL-1.2"
inceptionYear = "2026"
stereotype = "CLI"
tags = [ "java", "git", "cli" ]

links.bugTracker = "https://github.com/bmarwell/betterbranch/issues"
links.homepage = "https://github.com/bmarwell/betterbranch"
links.vcsBrowser = "https://github.com/bmarwell/betterbranch"

[release.github]
enabled = true
owner = "bmarwell"
name = "betterbranch"
username = "bmarwell"
update.enabled = true

    [release.github.changelog]
    formatted = "ALWAYS"
    preset = "conventional-commits"
    links = true
    hide.contributors = [ "Benjamin Marwell", "[bot]", "GitHub" ]

# Release the already-built archive artifacts from the artifact download step.
[distributions.betterbranch-archive]
type = "JAVA_BINARY"
stereotype = "CLI"

    [[distributions.betterbranch-archive.artifacts]]
    path = "{{artifactsDir}}/betterbranch-{{projectVersion}}.zip"

    [[distributions.betterbranch-archive.artifacts]]
    path = "{{artifactsDir}}/betterbranch-{{projectVersion}}.tar.gz"

# Release the native binaries downloaded from CI.
[distributions.betterbranch]
type = "BINARY"
stereotype = "CLI"

    [[distributions.betterbranch.artifacts]]
    path = "{{artifactsDir}}/betterbranch-{{projectVersion}}-linux-x86_64.zip"
    platform = "linux-x86_64"
    extraProperties.graalVMNativeImage = true

    [[distributions.betterbranch.artifacts]]
    path = "{{artifactsDir}}/betterbranch-{{projectVersion}}-linux-x86_64.tar.gz"
    platform = "linux-x86_64"
    extraProperties.graalVMNativeImage = true

    [[distributions.betterbranch.artifacts]]
    path = "{{artifactsDir}}/betterbranch-{{projectVersion}}-linux-aarch_64.zip"
    platform = "linux-aarch_64"
    extraProperties.graalVMNativeImage = true

    [[distributions.betterbranch.artifacts]]
    path = "{{artifactsDir}}/betterbranch-{{projectVersion}}-linux-aarch_64.tar.gz"
    platform = "linux-aarch_64"
    extraProperties.graalVMNativeImage = true

    [[distributions.betterbranch.artifacts]]
    path = "{{artifactsDir}}/betterbranch-{{projectVersion}}-windows-x86_64.zip"
    platform = "windows-x86_64"
    extraProperties.graalVMNativeImage = true

    [[distributions.betterbranch.artifacts]]
    path = "{{artifactsDir}}/betterbranch-{{projectVersion}}-osx-aarch_64.zip"
    platform = "osx-aarch_64"
    extraProperties.graalVMNativeImage = true
