name: Build

permissions:
  contents: read

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main, '*', '**/*' ]

jobs:
  build:
    if: github.event_name != 'push' || (contains(github.event.head_commit.message, 'Releasing version') != true && contains(github.event.head_commit.message, 'Prepare next version') != true)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0

      - name: Set up JDK
        uses: actions/setup-java@v6.0.0
        with:
          java-version: 25
          distribution: 'temurin'
          cache: maven

      - name: Cache Maven local repository
        id: restore-maven-package-cache
        uses: actions/cache@v6.1.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m22-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build and test all
        shell: bash
        run: |
          ./mvnw \
            --batch-mode \
            --show-version \
            --strict-checksums \
            --errors \
            --no-transfer-progress \
            spotless:check verify \
            -Dnative.skip=true

      - name: Save downloaded Maven packages
        uses: actions/cache/save@v6.1.0
        with:
          path: ~/.m2
          key: ${{ steps.restore-maven-package-cache.outputs.cache-hit }}
        if: github.event_name != 'pull_request'

  call-native:
    if: github.event_name != 'push' || (contains(github.event.head_commit.message, 'Releasing version') != true && contains(github.event.head_commit.message, 'Prepare next version') != true)
    needs: build
    uses: ./.github/workflows/build-native.yml
    with:
      head_sha: ${{ github.sha }}
    secrets: inherit
