name: Build Native

permissions:
  contents: read

on:
  workflow_call:
    inputs:
      head_sha:
        description: The commit SHA to checkout
        required: false
        type: string
      maven_profiles:
        description: Optional Maven profiles
        required: false
        type: string

jobs:
  # Build linux first for the jreleaser distro, and to see whether the native build will work
  # so we can skip win/mac if it doesn't.
  build-linux-x64:
    name: Build Linux x64
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          fetch-depth: 0
          ref: ${{ inputs.head_sha || github.sha }}

      - name: Install build dependencies on Linux
        if: runner.os == 'Linux'
        run: |
          sudo apt-get update
          sudo apt-get install -y build-essential zlib1g-dev

      - name: Set up JDK
        uses: actions/setup-java@v5.6.0
        with:
          java-version: 25
          distribution: graalvm
          cache: maven

      - name: Cache Maven packages
        id: restore-maven-package-cache
        uses: actions/cache/restore@v6.1.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build native executable
        shell: bash
        run: |
          PROFILE_ARGS=""
          if [ -n "${{ inputs.maven_profiles }}" ]; then
            PROFILE_ARGS="-P${{ inputs.maven_profiles }}"
          fi
          ./mvnw \
            --batch-mode \
            --show-version \
            --strict-checksums \
            --errors \
            --no-transfer-progress \
            ${PROFILE_ARGS} \
            package

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: artifacts-ubuntu-latest
          if-no-files-found: error
          path: |
            target/betterbranch*
            target/*.jar
            cli/target/jreleaser/assemble/betterbranch/java-archive/*.zip
            cli/target/jreleaser/assemble/betterbranch/java-archive/*.tar.gz

      - name: Save downloaded Maven packages
        uses: actions/cache/save@v6.1.0
        with:
          path: ~/.m2
          key: ${{ steps.restore-maven-package-cache.outputs.cache-primary-key }}
        if: github.event.workflow_run.event != 'pull_request'

  build-others:
    name: Build ${{ matrix.target }}
    needs: build-linux-x64
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - target: macos-aarch64
            os: macos-14
            arch: aarch64
          - target: windows-x64
            os: windows-2022
            arch: x64

    steps:
      - name: Checkout repository
        uses: actions/checkout@v7.0.1
        with:
          # Disabling shallow clone is recommended for improving relevancy of reporting
          fetch-depth: 0
          ref: ${{ inputs.head_sha || github.sha }}

      - name: Set up JDK
        uses: actions/setup-java@v5.6.0
        with:
          java-version: 25
          distribution: 'graalvm'
          cache: maven

      - name: Cache Maven packages
        id: restore-maven-package-cache
        uses: actions/cache/restore@v6.1.0
        with:
          path: ~/.m2
          key: ${{ runner.os }}-m2-${{ hashFiles('**/pom.xml') }}
          restore-keys: ${{ runner.os }}-m2

      - name: Build static native image for Linux
        if: matrix.os == 'ubuntu-latest'
        run: |
          PROFILE_ARGS="-Plinux"
          if [ -n "${{ inputs.maven_profiles }}" ]; then
            PROFILE_ARGS="-P${{ inputs.maven_profiles }},linux"
          fi
          ./mvnw \
            --batch-mode \
            --show-version --strict-checksums --errors --no-transfer-progress \
            ${PROFILE_ARGS} \
            package

      - name: Build static native image for Windows / macOS
        if: matrix.os != 'ubuntu-latest'
        shell: bash
        run: |
          PROFILE_ARGS="-Plinux"
          if [ -n "${{ inputs.maven_profiles }}" ]; then
            PROFILE_ARGS="-P${{ inputs.maven_profiles }}"
          fi
          ./mvnw \
            --batch-mode \
            --show-version --strict-checksums --errors --no-transfer-progress \
            ${PROFILE_ARGS} \
            package

      - name: Save downloaded Maven packages
        uses: actions/cache/save@v6.1.0
        with:
          path: ~/.m2
          key: ${{ steps.restore-maven-package-cache.outputs.cache-primary-key }}
        if: github.event.workflow_run.event != 'pull_request'

      - name: Upload build artifacts
        uses: actions/upload-artifact@v7.0.1
        with:
          name: artifacts-${{ matrix.os }}
          path: |
            cli/target/distributions/*.zip
            cli/target/distributions/*.tar.gz

